---
title: "UTCI Analysis"
format: html
editor: visual
---

# Environment Setup

```{r setup}
# Packages
library(tidyverse)
library(tidyterra)
library(sf)
library(paletteer)
library(patchwork)

# Path Structure
root <- rprojroot::has_file("agile2025.Rproj")$make_fix_file()
raw_data_dir <- root("data/raw")
proc_data_dir <- root("data/processed/population")
dir.create(proc_data_dir, showWarnings = FALSE)
fig_dir <- root("figures")
```

# Data Import

## Geographies

### Mozambique

```{r}
sf_moz <- (
  st_read(
    file.path(raw_data_dir, "geographies", "Mozambique 2022 DHS - sdr_subnational_boundaries", "shps", "sdr_subnational_boundaries.shp")
  )
  %>% rename_with(tolower)
  %>% select(
    country = cntrynamee,
    adm_name = dhsregen,
    adm_code = regcode
  )
  %>% arrange(adm_code)
)
```

### Zimbabwe

```{r}
sf_zwe <- (
  st_read(
    file.path(raw_data_dir, "geographies", "Zimbabwe 2015 DHS - sdr_subnational_boundaries", "shps", "sdr_subnational_boundaries.shp")
  )
  %>% rename_with(tolower)
  %>% select(
    country = cntrynamee,
    adm_name = dhsregen,
    adm_code = regcode
  )
  %>% arrange(adm_code)
)
```

### Lesotho

```{r}
sf_lso <- (
  st_read(
    file.path(raw_data_dir, "geographies", "Lesotho 2023 DHS - sdr_subnational_boundaries", "shps", "sdr_subnational_boundaries.shp")
  )
  %>% rename_with(tolower)
  %>% select(
    country = cntrynamee,
    adm_name = dhsregen,
    adm_code = regcode
  )
  %>% arrange(adm_code)
)
```

### Namibia

```{r}
sf_nam <- (
  st_read(
    file.path(raw_data_dir, "geographies", "Namibia 2013 DHS - sdr_subnational_boundaries", "shps", "sdr_subnational_boundaries.shp")
  )
  %>% rename_with(tolower)
  %>% select(
    country = cntrynamee,
    adm_name = dhsregen,
    adm_code = regcode
  )
  %>% arrange(adm_code)
)
```

### Zambia

```{r}
sf_zmb <- (
  st_read(
    file.path(raw_data_dir, "geographies", "Zambia 2018 DHS - sdr_subnational_boundaries", "shps", "sdr_subnational_boundaries.shp")
  )
  %>% rename_with(tolower)
  %>% select(
    country = cntrynamee,
    adm_name = dhsregen,
    adm_code = regcode
  )
  %>% arrange(adm_code)
)
```

### Uganda

```{r}
sf_uga <- (
  st_read(
    file.path(
      raw_data_dir,
      "geographies",
      "uganda_herbert",
      "uganda_districts.shp"
    ),
  )
  %>% rename_with(tolower)
  %>% mutate(
    country = "Uganda",
    district = case_match(
      district,
      "SSEMBABULE" ~ "Sembabule",
      "KASSNDA" ~ "Kassanda",
      "MADI OKOLLO" ~ "Madi-Okollo",
      "NAMUTUNMBA" ~ "Namutumba",
      .default = str_to_title(district)
    )
  )
  %>% select(
    country,
    adm_code = objectid,
    adm_name = district
  )
  %>% st_transform(4326)
)
```

### Kenya

```{r}
sf_ken <- (
  st_read(
    file.path(raw_data_dir, "geographies", "Kenya 2022 DHS - sdr_subnational_boundaries_2025-11-13", "shps", "sdr_subnational_boundaries.shp")
  )
  %>% rename_with(tolower)
  %>% select(
    country = cntrynamee,
    adm_name = dhsregen,
    adm_code = regcode
  )
  %>% arrange(adm_code)
)
```

## Population

### Mozambique

```{r}
rast_pop_moz <- (
  terra::rast(
    file.path(raw_data_dir, "population", "moz_pop_2019_CN_1km_R2025A_UA_v1.tif")
  )
  %>% rename(
    pop = global_pop_2019_CN_1km_R2025A_v1
  )
)
```

```{r}
adm_pop_moz <- (
  rast_pop_moz
  %>% exactextractr::exact_extract(
    sf_moz,
    fun = function(values, coverage_fraction) sum(values * coverage_fraction, na.rm = TRUE),
    max_cells_in_memory = 176067000,
    append_cols = c("country", "adm_code", "adm_name")
  )
  %>% rename(
    pop = result
  )
)
```

### Zimbabwe

```{r}
rast_pop_zwe <- (
  terra::rast(  
    file.path(raw_data_dir, "population", "zwe_pop_2017_CN_1km_R2025A_UA_v1.tif")
  )
  %>% rename(
    pop = global_pop_2017_CN_1km_R2025A_v1
  )
)
```

```{r}
adm_pop_zwe <- (
  rast_pop_zwe
  %>% exactextractr::exact_extract(
    sf_zwe,
    fun = function(values, coverage_fraction) sum(values * coverage_fraction, na.rm = TRUE),
    max_cells_in_memory = 176067000,
    append_cols = c("country", "adm_code", "adm_name")
  )
  %>% rename(
    pop = result
  )
)
```

### Lesotho

```{r}
rast_pop_lso <- (
  terra::rast(
    file.path(raw_data_dir, "population", "lso_pop_2018_CN_1km_R2025A_UA_v1.tif")
  )
  %>% rename(
    pop = global_pop_2018_CN_1km_R2025A_v1
  )
)
```

```{r}
adm_pop_lso <- (
  rast_pop_lso
  %>% exactextractr::exact_extract(
    sf_lso,
    fun = function(values, coverage_fraction) sum(values * coverage_fraction, na.rm = TRUE),
    max_cells_in_memory = 176067000,
    append_cols = c("country", "adm_code", "adm_name")
  )
  %>% rename(
    pop = result
  )
)
```

### Namibia

```{r}
rast_pop_nam <- (
  terra::rast(
    file.path(raw_data_dir, "population", "nam_pop_2019_CN_1km_R2025A_UA_v1.tif")
  )
  %>% rename(
    pop = global_pop_2019_CN_1km_R2025A_v1
  )
)
```

```{r}
adm_pop_nam <- (
  rast_pop_nam
  %>% exactextractr::exact_extract(
    sf_nam,
    fun = function(values, coverage_fraction) sum(values * coverage_fraction, na.rm = TRUE),
    max_cells_in_memory = 176067000,
    append_cols = c("country", "adm_code", "adm_name")
  )
  %>% rename(
    pop = result
  )
)
```

### Zambia

```{r}
rast_pop_zmb <- (
  terra::rast(
    file.path(raw_data_dir, "population", "zmb_pop_2015_CN_1km_R2025A_UA_v1.tif")
  )
  %>% rename(
    pop = global_pop_2015_CN_1km_R2025A_v1
  )
)
```

```{r}
adm_pop_zmb <- (
  rast_pop_zmb
  %>% exactextractr::exact_extract(
    sf_zmb,
    fun = function(values, coverage_fraction) sum(values * coverage_fraction, na.rm = TRUE),
    max_cells_in_memory = 176067000,
    append_cols = c("country", "adm_code", "adm_name")
  )
  %>% rename(
    pop = result
  )
)
```

### Uganda

```{r}
rast_pop_uga <- (
  terra::rast(
    file.path(raw_data_dir, "population", "uga_pop_2024_CN_1km_R2025A_UA_v1.tif")
  )
  %>% rename(
    pop = global_pop_2024_CN_1km_R2025A_v1
  )
)
```

```{r}
adm_pop_uga <- (
  rast_pop_uga
  %>% exactextractr::exact_extract(
    sf_uga,
    fun = function(values, coverage_fraction) sum(values * coverage_fraction, na.rm = TRUE),
    max_cells_in_memory = 176067000,
    append_cols = c("country", "adm_code", "adm_name")
  )
  %>% rename(
    pop = result
  )
)
```

### Kenya

```{r}
rast_pop_ken <- (
  terra::rast(
    file.path(raw_data_dir, "population", "ken_pop_2018_CN_1km_R2025A_UA_v1.tif")
  )
  %>% rename(
    pop = global_pop_2018_CN_1km_R2025A_v1
  )
)
```

```{r}
adm_pop_ken <- (
  rast_pop_ken
  %>% exactextractr::exact_extract(
    sf_ken,
    fun = function(values, coverage_fraction) sum(values * coverage_fraction, na.rm = TRUE),
    max_cells_in_memory = 176067000,
    append_cols = c("country", "adm_code", "adm_name")
  )
  %>% rename(
    pop = result
  )
)
```

### Create combined dataset

```{r}
adm_pop <- (
  bind_rows(
    adm_pop_moz,
    adm_pop_zwe,
    adm_pop_lso,
    adm_pop_nam,
    adm_pop_zmb,
    adm_pop_uga,
    adm_pop_ken
  )
)
```

# Save

```{r}
adm_pop %>% write_csv(file.path(proc_data_dir, "adm_pop_all_countries.csv"))
```
